config/routes.rb
Dtechbots::Application.routes.draw do
    
  

  root to: 'admins#index'
  

  resources :admins
  resources :sessions
  resources :inventories
  resources :orders
  resources :members
  resources :line_items
  resources :carts
  resources :member_session

 
 

  match 'member_pages/index',       to: 'manage_member_pages#index'
  match 'member_pages/home',        to: 'manage_member_pages#home'
  match 'member_pages/inventory',   to: 'manage_member_pages#listInventory'
  match 'member_pages/createOrder', to: 'manage_member_pages#createOrder'

    
 
  get 'login' , to: 'sessions#new',     as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get "/member",to: 'manage_member_pages#index'
  get '/member_login' , to: 'member_session#new',  as: 'member_login'

  

   match ':controller(/:action(/:id))(.:format)'
   

  

end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  attr_accessible :bk_name, :bk_price,:bk_author

  default_scope :order => 'created_at'

  has_many :line_items
  
  before_destroy :ensure_not_referenced_by_any_line_item
#

  validates :bk_name, presence: true  
  validates :bk_price, presence: true

# ensure that there are no line items referencing this book in the inventory
	def ensure_not_referenced_by_any_line_item
		if line_items.count.zero?
			return true
		else
			errors[:base] << "Line Items present"
			return false
		end
	end

end

 

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  # GET /inventories
  # GET /inventories.json
  layout 'admin'

  before_filter :confirm_admin_logged_in
 

  def index
    @inventories = Inventory.order("inventories.created_at DESC").paginate(page: params[:page],per_page: 5)
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @inventories }
    end
  end

  # GET /inventories/1
  # GET /inventories/1.json
  def show
    @inventory = Inventory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @inventory }
    end
  end

  # GET /inventories/new
  # GET /inventories/new.json
  def new
    @inventory = Inventory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @inventory }
    end
  end

 

  # POST /inventories
  # POST /inventories.json
  def create
    @inventory = Inventory.new(params[:inventory])

    respond_to do |format|
      if @inventory.save
        format.html { redirect_to @inventory, notice: 'Inventory was successfully created.' }
        format.json { render json: @inventory, status: :created, location: @inventory }
      else
        format.html { render action: "new" }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

   # GET /inventories/1/edit
  def edit
    @inventory = Inventory.find(params[:id])
  end

  # PUT /inventories/1
  # PUT /inventories/1.json
  def update
    @inventory = Inventory.find(params[:id])

    respond_to do |format|
      if @inventory.update_attributes(params[:inventory])
        format.html { redirect_to @inventory, notice: 'Inventory was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventories/1
  # DELETE /inventories/1.json
  def destroy
    @inventory = Inventory.find(params[:id])
    @inventory.destroy

    respond_to do |format|
      format.html { redirect_to inventories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/_form.html.erb
<%= form_for @inventory, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :bk_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :bk_name, :class => 'text_field' %>
    </div>
  </div>

   <div class="control-group">
    <%= f.label :bk_author, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :bk_author, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :bk_price, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :bk_price, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                inventories_path, :class => 'btn' %>
  </div>
<% end %>

app/views/inventories/edit.html.erb
<%- model_class = Inventory -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/inventories/index.html.erb
<%- model_class = Inventory -%>
<div class="page-header">
  <h3 class="glyphicon glyphicon-gift"><%=Inventory%></h3>
</div>

<div class="pagination">
  <%= will_paginate @inventories, renderer: BootstrapPagination::Rails %>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:ID) %></th>
      <th><%= model_class.human_attribute_name(:Name) %></th>
      <th><%= model_class.human_attribute_name(:Author) %></th>
      <th><%= model_class.human_attribute_name(:Price) %>(Rs)</th>
      <th><%= model_class.human_attribute_name(:created_at) %>(UTC)</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @inventories.each do |inventory| %>
      <tr>
        <td>#<%= link_to inventory.id, inventory_path(inventory) %></td>
        <td><%= inventory.bk_name %></td>
        <td><%= inventory.bk_author %></td>
        <td><%= inventory.bk_price %></td>
        <td><%= inventory.created_at.strftime("%m/%d/%Y %I:%M%p")%></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_inventory_path(inventory), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      inventory_path(inventory),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_inventory_path,
            :class => 'btn btn-primary' %>

app/views/inventories/new.html.erb
<%- model_class = Inventory -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/inventories/show.html.erb
<%- model_class = Inventory -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:bk_name) %>:</strong></dt>
  <dd><%= @inventory.bk_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:bk_price) %>:</strong></dt>
  <dd><%= @inventory.bk_price %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              inventories_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_inventory_path(@inventory), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              inventory_path(@inventory),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>