config/routes.rb
Dtechbots::Application.routes.draw do
    
  

  root to: 'admins#index'
  

  resources :admins
  resources :sessions
  resources :inventories
  resources :orders
  resources :members
  resources :line_items
  resources :carts
  resources :member_session

 
 

  match 'member_pages/index',       to: 'manage_member_pages#index'
  match 'member_pages/home',        to: 'manage_member_pages#home'
  match 'member_pages/inventory',   to: 'manage_member_pages#listInventory'
  match 'member_pages/createOrder', to: 'manage_member_pages#createOrder'

    
 
  get 'login' , to: 'sessions#new',     as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get "/member",to: 'manage_member_pages#index'
  get '/member_login' , to: 'member_session#new',  as: 'member_login'

  

   match ':controller(/:action(/:id))(.:format)'
   

  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
 
  has_secure_password
  attr_accessible :password_digest, :username, :password, :password_confirmation

  validates_uniqueness_of :username


end

app/models/cart.rb
class Cart < ActiveRecord::Base
  # attr_accessible :title, :body

  has_many :line_items, :dependent => :destroy
  belongs_to :member
 
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  attr_accessible :bk_name, :bk_price,:bk_author

  default_scope :order => 'created_at'

  has_many :line_items
  
  before_destroy :ensure_not_referenced_by_any_line_item
#

  validates :bk_name, presence: true  
  validates :bk_price, presence: true

# ensure that there are no line items referencing this book in the inventory
	def ensure_not_referenced_by_any_line_item
		if line_items.count.zero?
			return true
		else
			errors[:base] << "Line Items present"
			return false
		end
	end

end

 

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  attr_accessible :cart_id, :inventory_id,:bk_qty
  belongs_to :inventory
  belongs_to :cart
end

app/models/member.rb
class Member < ActiveRecord::Base
  
  has_secure_password
  attr_accessible :first_name, :last_name, :password_digest,
  					 :username,:password, :password_confirmation

 has_one :cart

  validates_uniqueness_of :username
  validates :password, length:{minimum:6}
  validates :password_confirmation, presence: true , on: :create

end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :bk_name, :bk_qty, :order_status
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController


	layout 'admin'
	  before_filter :confirm_admin_logged_in

	def index
		 @admin ||= Admin.find(session[:admin_id]) if session[:admin_id]
	end

	def show
		 @admin ||= Admin.find(session[:admin_id]) if session[:admin_id]
	end

	def new
	  @admin = Admin.new
	end

	def create
	  @admin = Admin.new(params[:admin])
	  if @admin.save
	    session[:admin_id] = @admin.id
	    redirect_to root_url, notice: "Thank you for signing up!"
	  else
	    render "new"
	  end
	end

	def edit
		 @admin=Admin.find(params[:id])
	end

	def update

        @admin=Admin.find(params[:id])
 
        @admin.update_attributes(params[:admin])
           
           if @admin.save
   
             flash[:success]= "Admin details for --"+@admin.username+"--updated successfully"
             redirect_to admin_path(current_admin)
           else
              flash[:warning]= "Admin details for"+ @admin.username+" cannot be updated. "
             render('edit')
           end

	end


end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # GET /carts
  # GET /carts.json

    layout 'member'

  before_filter :confirm_member_logged_in
  
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    @cart = Cart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy

    respond_to do |format|
      format.html { redirect_to carts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	layout 'admin'
	  before_filter :confirm_admin_logged_in

  def index
  	   @orders=Order.order("orders.created_at DESC").paginate(page: params[:page],per_page: 5)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  layout 'admin'

  #before_filter :confirm_admin_logged_in
   before_filter :confirm_member_logged_in


  def index

    @orders=Order.order("orders.created_at DESC").paginate(page: params[:page],per_page: 5)

  end

  def show
  end

  def new
  end


  def create

     

    @order=Order.new
    @line_items=LineItem.where(:cart_id=>current_cart.id)
    @inventories=Inventory.all
 
    @line_items.each do |line_item|
        @inventories.each do |inventory|
                    if line_item.inventory_id==inventory.id
                      @order.bk_name=inventory.bk_name
                      @order.bk_qty=line_item.bk_qty
                      @order.order_status="OPEN"
                       
                  end
        end

      @order.save
      @order=Order.new

    end


    
     

  end




  def edit
    @order=Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to orders_path, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end
end

  

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admins/edit.html.erb
 
<div class="container">
 
	  <div class="page-header">
		<h3>Change Settings</h3>
	</div>
	<div class="row">
		<div class="span6 offset1">

  		 <%=form_for(@admin,:url=>{:action=>'update',:id =>@admin.id}) do |f| %>
  		 
			  

				<table class="table table-striped">
					 <thead>
					 	<h4>Admin Credentials</h4></thead>
						<tr>
							<th>Username</th>
								
							<td><%=f.text_field(:username)%></td>
						</tr>
						<tr>
							<th>Password  </th>
							<td><%=f.password_field(:password)%></td>
						</tr>
						<tr><td></td>
							<td> 	
							  <%=submit_tag "Modify" ,:class=>"btn" %> 	 
							 <%=link_to("Cancel",{:action=>'index'},:class=>"btn")%>
							</td>
						</tr>
					 
				<%end%>
				</table>


		</div></b></div>
</div>

app/views/admins/index.html.erb
<div class="page-header">
	<h3 class="glyphicon glyphicon-home">Welcome Admin</h3>
</div>

<div id="adminpanel">
		<img src="assets/supadmin.png">
</div>

app/views/admins/show.html.erb
	<div class="page-header">
		<h3 class="glyphicon glyphicon-wrench">Manage Profile</h3>
	</div>

	<div class="container-fluid">  
  		<div class="row-fluid"> 
  			
  			<div class="span4">
  				<table class="table">
  					<thead><h6>Account Settings</h6></thead>
  					<tr>
  						<th>Username</th>
  					</tr>
  					
  					<tr>
  						<td><%=@admin.username%></td>		
  				   </tr>
  				   	<tr>
  				  		 <th>Password</th>
  				   </tr>
  					<tr>
  						<td>******************</td>
  				   </tr>
  				   <tr>
  				   <td><%=link_to "Modify",edit_admin_path, class:"btn"%></td>
  				</tr>
  					
  				</table>
  			</div>
  			 
  		</div>
  	</div

app/views/layouts/admin.html.erb
  <!DOCTYPE html>
<html>
<head>
  <title>Dtechbots</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>

  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>


<div class="navbar navbar-fixed-top">  
  <div class="navbar-inner">  
    <div class="container">  
      <ul class="nav nav-pills nav-stacked">  

        <% if current_admin %>
              <li><%=link_to "Home",admins_path,class:"glyphicon glyphicon-home"%></li>
              <li><%=link_to "Dashboard",{:controller=>"home",:action=>"index"},class:"glyphicon glyphicon-dashboard"%></li>
              <li><%=link_to "Inventory", inventories_path,class:"glyphicon glyphicon-gift" %>  </li>  
              <li><%=link_to "Orders",orders_path,class:"glyphicon glyphicon-shopping-cart" %>  </li>
           

            <ul class="nav">  
              <li class="dropdown">  
                <a href="#"  
                      class="dropdown-toggle"  
                      data-toggle="dropdown">  
                        <span class="glyphicon glyphicon-user"><%=current_admin.username%></span>     
                      <b class="caret"></b>  
                </a>  
                <ul class="dropdown-menu">  
                    <li><%=link_to " Logout ", logout_path,class:"glyphicon glyphicon-off" %>  </li>

           

                </ul>  
              </li>  
           </ul> 
        <% else %>
          <%= link_to "Sign Up", signup_path %> or
          <%= link_to "Log In", login_path %>
        <% end %>
          
  		     
		</ul>  
    </div>  
  </div>  
</div>
 

	<div class="container-fluid">  
  <div class="row-fluid"> 

    <div class="span2" id="sidebar">  
      <!--Sidebar content-->  
       <ul class="nav nav-pills nav-stacked">  
          <% if current_admin %>
 
        		  <li><%=link_to "Home",admins_path,class:"glyphicon glyphicon-home"%></li>    
               <li><%=link_to "Dashboard",{:controller=>"home",:action=>"index"},class:"glyphicon glyphicon-dashboard"%></li>  
               <li><%=link_to "Inventory",inventories_path,class:"glyphicon glyphicon-gift" %>  </li>   
        			 <li><%=link_to "Orders",orders_path,class:"glyphicon glyphicon-shopping-cart" %>  </li>  
               <li><%=link_to "Profile",admin_path(current_admin),class:"glyphicon glyphicon-wrench" %>  </li> 
           
               <li><%=link_to "Members",members_path,class:"glyphicon glyphicon-user" %>  </li> 
               <li><%=link_to "Admins", "",class:"glyphicon glyphicon-user" %>  </li>   
                <li><%=link_to " Logout ", logout_path,class:"glyphicon glyphicon-off" %>  </li>
          <%end%>
		</ul>  
 
    </div>  
    <div class="span10" id="mainBody">  
    	<%= yield %>
      <!--Body content-->  
      <footer id="footer">
        @Simi Tresa Antony 2014</footer>
    </div>  
  </div>  
</div>  
  


</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dtechbots</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<% if notice %>
 		 <p class="alert alert-success"><%= notice %></p>
	<% end %>
	<% if alert %>
	 <p class="alert alert-danger"><%= alert %></p>
	<% end %>


<%= yield %>

</body>
</html>

app/views/layouts/fluid.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Dtechbots" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Dtechbots</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                <li><%= link_to "Link1", "/path1"  %></li>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/member.html.erb
  <!DOCTYPE html>
<html>
<head>
  <title>Dtechbots</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>

  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body class="backgroundColor">



<div class="navbar navbar-fixed-top">  
  <div class="navbar-inner">  
    <div class="container">  
      <ul class="nav nav-pills nav-stacked">  

          <%if current_member%>
              <li><%=link_to "Home", member_pages_index_path,class:"glyphicon glyphicon-home"%></li>
              <li><%=link_to "Inventory",member_pages_inventory_path,class:"glyphicon glyphicon-gift" %>  </li>  
              <li><%=link_to "Manage Orders","",class:"glyphicon" %>  </li>
               <li><%=link_to "Cart",line_items_path,class:"glyphicon glyphicon-shopping-cart" %>  </li>

            <ul class="nav">  
              <li class="dropdown">  
                <a href="#"  
                      class="dropdown-toggle"  
                      data-toggle="dropdown">  
                        <span class="glyphicon glyphicon-user"><%=%></span>     
                      <b class="caret"></b>  
                </a>  
                <ul class="dropdown-menu">  
                    <li><%=link_to " Logout ",member_session_path(current_member),
                                            :method => :delete,class:"glyphicon glyphicon-off" %>  </li>

                </ul>  
              </li>  
           </ul>    
  		     

		</ul>  


    </div>  
  </div>  
</div>
  <%end%>

	<div class="container-fluid">  
  <div class="row-fluid"> 

    <div class="span2" id="sidebar">  
      <!--Sidebar content-->  
       <ul class="nav nav-pills nav-stacked">  
        
 
        		  <li><%=link_to "Home",member_pages_index_path,class:"glyphicon glyphicon-home"%></li>      
               <li><%=link_to "Inventory",member_pages_inventory_path,class:"glyphicon glyphicon-gift" %>  </li>   
        			 <li><%=link_to "Orders","",class:"glyphicon glyphicon-shopping-cart" %>  </li>  
               <li><%=link_to "Profile","",class:"glyphicon glyphicon-wrench" %>  </li> 
               <li><%=link_to " Logout ",member_session_path(current_member),
                                            :method => :delete,class:"glyphicon glyphicon-off" %>  </li>
         
		</ul>  
 
    </div>  
    <div class="span10" >  
    	<%= yield %>
      <!--Body content-->  
      <footer id="footer">
        @Simi Tresa Antony 2014</footer>
    </div>  
  </div>  
</div>  
  


</body>
</html>