config/routes.rb
Dtechbots::Application.routes.draw do
    
  

  root to: 'admins#index'
  

  resources :admins
  resources :sessions
  resources :inventories
  resources :orders
  resources :members
  resources :line_items
  resources :carts
  resources :member_session

 
 

  match 'member_pages/index',       to: 'manage_member_pages#index'
  match 'member_pages/home',        to: 'manage_member_pages#home'
  match 'member_pages/inventory',   to: 'manage_member_pages#listInventory'
  match 'member_pages/createOrder', to: 'manage_member_pages#createOrder'

    
 
  get 'login' , to: 'sessions#new',     as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get "/member",to: 'manage_member_pages#index'
  get '/member_login' , to: 'member_session#new',  as: 'member_login'

  

   match ':controller(/:action(/:id))(.:format)'
   

  

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  # attr_accessible :title, :body

  has_many :line_items, :dependent => :destroy
  belongs_to :member
 
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # GET /carts
  # GET /carts.json

    layout 'member'

  before_filter :confirm_member_logged_in
  
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    @cart = Cart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy

    respond_to do |format|
      format.html { redirect_to carts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<div class="page-header">
  <h3>Listing cart items</h3>
</div>

<%index=0%>

<table class="table" id="members_table">
   <thead> 
    <tr>
       <th>Item Index</th>
      <th>Item Name</th>
       <th>Item QTY</th>
      <th>Actions</th>
    </tr></thead>

  <tr>
        <%current_cart.line_items.each do |line_item| %>
          <td>#<%=index=index+1%> </td>
          <td><%= line_item.inventory.bk_name%></td>
          <td><%= line_item.bk_qty%></td>
            
             <td>  <%= link_to 'Modify',edit_line_item_path(line_item),class:"btn"%></td>
             <td><%= link_to 'Remove',line_item_path(line_item), 
                                   method: :delete, 
                                   class:"btn btn-danger",
                                   data: { confirm: 'Are you sure?' } 
                                   %></td>
        
         
  </tr>
  <%end%>
</table>

       <%=link_to "Place Order","",class:"btn btn-danger"%> 
 

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Your Pragmatic Cart</h2>
 
  
        <%=current_cart.line_items%>

 
 
    <td><%= link_to 'Edit', edit_cart_path(current_cart) %></td>
    <td><%= link_to 'Destroy', current_cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
 
 


 