config/routes.rb
Dtechbots::Application.routes.draw do
    
  

  root to: 'admins#index'
  

  resources :admins
  resources :sessions
  resources :inventories
  resources :orders
  resources :members
  resources :line_items
  resources :carts
  resources :member_session

 
 

  match 'member_pages/index',       to: 'manage_member_pages#index'
  match 'member_pages/home',        to: 'manage_member_pages#home'
  match 'member_pages/inventory',   to: 'manage_member_pages#listInventory'
  match 'member_pages/createOrder', to: 'manage_member_pages#createOrder'

    
 
  get 'login' , to: 'sessions#new',     as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get "/member",to: 'manage_member_pages#index'
  get '/member_login' , to: 'member_session#new',  as: 'member_login'

  

   match ':controller(/:action(/:id))(.:format)'
   

  

end

app/models/member.rb
class Member < ActiveRecord::Base
  
  has_secure_password
  attr_accessible :first_name, :last_name, :password_digest,
  					 :username,:password, :password_confirmation

 has_one :cart

  validates_uniqueness_of :username
  validates :password, length:{minimum:6}
  validates :password_confirmation, presence: true , on: :create

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  
  layout 'admin'

  before_filter :confirm_admin_logged_in

  # GET /members
  # GET /members.json
  def index
    @members = Member.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @members }
    end
  end

  def show
    @member = Member.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @member }
    end
  end


  # GET /members/new
  # GET /members/new.json
  def new
    @member = Member.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @member }
    end
  end

 

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(params[:member])

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render json: @member, status: :created, location: @member }
      else
        format.html { render action: "new" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end



 # GET /members/1/edit
  def edit
    @member = Member.find(params[:id])
  end
  # PUT /members/1
  # PUT /members/1.json
  def update
    @member = Member.find(params[:id])

    respond_to do |format|
      if @member.update_attributes(params[:member])
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member = Member.find(params[:id])
    @member.destroy

    respond_to do |format|
      format.html { redirect_to members_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password%>
  </div>
   <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation%>
  </div>
  <div class="actions">
       <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to 'Back', members_path,class:"btn"  %>
  </div>
<% end %>

app/views/members/edit.html.erb
<div class="page-header">
	<h3>Modify Member Details</h3>
</div>

 

<%= render 'form' %>

 

app/views/members/index.html.erb
<div class="page-header">
	<h3 class="glyphicon glyphicon-user">Manage Members</h3>
</div>
 
<table class="table table-striped">
  <tr>
    <th>Username</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Actions</th>
  </tr>

<% @members.each do |member| %>
  <tr>
    <td><%= member.username %></td>
    <td><%= member.first_name %></td>
    <td><%= member.last_name %></td>  
    <td><%= link_to 'Modify', edit_member_path(member),class:"btn" %>
    <%= link_to 'Remove',member_path(member), method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-danger" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New', new_member_path ,class:"btn btn-primary" %>
 

app/views/members/new.html.erb
<div class="page-header">
	<h3>Create new member</h3>
</div>

<%= render 'form' %>

 

app/views/members/show.html.erb
<div class="page-header">
	<h3>Show Member</h3>
</div>

<p id="notice" class="alert"><%= notice %></p>


<table class="table table-striped">

	<thead>
		<tr>
			<th>Username</th>
			<th>First name:</th>
			<th>Last name:</th>
		</tr>
	</thead>

	<tbody><tr>
		<td> <%= @member.username %></td>
		<td> <%= @member.first_name %></td>
		<td> <%= @member.last_name %></td>
	 
		</tr>
    </tbody> 

</table>

<%= link_to 'Edit', edit_member_path(@member),class:"btn" %> |
<%= link_to 'Back', members_path,class:"btn" %>